# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import olca_pb2 as olca__pb2

from olca_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='protolca.services',
  syntax='proto3',
  serialized_options=b'\n\032org.openlca.proto.services',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eservices.proto\x12\x11protolca.services\x1a\nolca.proto28\n\x0cModelService\x12(\n\x07getFlow\x12\r.protolca.Ref\x1a\x0e.protolca.FlowB\x1c\n\x1aorg.openlca.proto.servicesP\x00\x62\x06proto3'
  ,
  dependencies=[olca__pb2.DESCRIPTOR,],
  public_dependencies=[olca__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_MODELSERVICE = _descriptor.ServiceDescriptor(
  name='ModelService',
  full_name='protolca.services.ModelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=49,
  serialized_end=105,
  methods=[
  _descriptor.MethodDescriptor(
    name='getFlow',
    full_name='protolca.services.ModelService.getFlow',
    index=0,
    containing_service=None,
    input_type=olca__pb2._REF,
    output_type=olca__pb2._FLOW,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVICE)

DESCRIPTOR.services_by_name['ModelService'] = _MODELSERVICE

# @@protoc_insertion_point(module_scope)
